name: Go Unit Tests

on: [push, pull_request]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20' 

    - name: Run majority_element_test
      run : go test ./top_interview_150/majotiry_element

    - name: Run merge_sorted_array
      run : go test ./top_interview_150/merge_sorted_array

    - name: Run remove_element
      run : go test ./top_interview_150/remove_element

    - name: Run rotate_array
      run : go test ./top_interview_150/rotate_array

    - name: Run valid_palindrome
      run : go test ./top_interview_150/valid_palindrome

    - name: Run max_depth_of_binary_tree
      run : go test ./top_interview_150/max_depth_of_binary_tree
